// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyBoKrQwFbgSyBUZ3mL6nmQdzYL8NT_hNZg',
    // appId: '1:709321081165:android:963ca36d3ecc1e3358f704',
    // messagingSenderId: '709321081165',
    // projectId: 'todo-app-18e97',
    // storageBucket: 'todo-app-18e97.appspot.com',

    apiKey: 'AIzaSyDYYlI7gBerelcr6ByleO3SlqEVug58dkY',
    appId: '1:678652111557:android:6cebb869a9cbaf0eac1eac',
    messagingSenderId: '678652111557',
    projectId: 'test-todos-app',
    storageBucket: 'test-todos-app.appspot.com',
  );

}
